name: Selo
favicon: null
layout_spectrum: 0.11193
typography_spectrum: 0.22797
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6875
  lightness: 0.8940159287303686
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
